config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  #all articles
  resources :articles

  #all categories
  resources :categories, except: [:destroy]
  
  #all users
  get 'signup', to: 'users#new'
  resources :users, except:[:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum:3, maximum:50}
    validates :description, presence: true, length: {minimum:10, maximum:10000}
    validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {minimum:3, maximum:25}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase}
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum:3, maximum:25}
    validates :email, presence: true, length: { maximum:100}, uniqueness: { case_sensitive: false }, format: {with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/}
    has_secure_password
    private
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
    
    def current_user
        #Use memoization to check if logged in
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end
    
    def require_user
        if !logged_in?
            flash[:danger] = "you must be logged in"
            redirect_to root_path
        end
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only:[:edit,:update,:show,:destroy]
    before_action :require_user, except: [:index,:show]
    before_action :require_same_user, only: [:edit,:update,:destroy]
    def index
        @articles = Article.paginate(page:params[:page],per_page:5)
    end
    def new
        @article = Article.new
    end
    def edit
    end
    
    def create
        #just check if params are passing
        #render plain: params[:article].inspect

        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)    
        else
            render 'new'
        end
    end
    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)    
        else
            render 'edit'
        end
        
    end
    

    def show
    end
    
    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
        
    end
    private
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title,:description,category_ids: [])
    end
    
    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "you can only edit or delete your own articles"
            redirect_to root_path
        end
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index,:show]
    def index
        @categories = Category.paginate(page: params[:page], per_page:5)
    end

    def new
        @category = Category.new
    end
    
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was created"
            redirect_to categories_path
        else 
            flash[:warning] = "There was a problem"
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Name updated successfully"
            redirect_to category_path(@category)
        else
            flash[:danger] = "there was a problem"
            render 'edit'
        end
    end
    
    private
    def category_params
        params.require(:category).permit(:name)
        
    end
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Only admin can perform this action"
            redirect_to categories_path
        end
        
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about
        
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
        user = User.find_by(email:params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You are logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Login failed"
            render 'new'
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:warning] = "You are logged out"
        redirect_to login_path
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit,:update]
    before_action :require_admin, only: [:destroy]
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "welcome to the alpha blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end
    def edit
        
    end
    def update
        
        if @user.update(user_params)
            flash[:success] = "Your account was updated !"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def show
        
        @user_articles = @user.articles.paginate(page:params[:page],per_page:3)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles have been deleted"
        redirect_to users_path
    end
    
    
    def index
        @users = User.all
        
    end
    
    
    private
    def user_params
        params.require(:user).permit(:username,:email,:password)
        
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "Forbidden !"
            redirect_to root_path
        end
    end
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin can perform that action"
            redirect_to root_path
        end
        
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class:"rounded-circle")
    end
    
end

app/views/articles/_form.html.erb
<%= render  "shared/errors", obj: @article %>
<div class="row">
  <div class="col-12">
    <%= form_for @article do |f|%>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description,rows: 10,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
          <% cb.label(class: "checkbox-inline input_checkbox mr-4") {cb.check_box(class: "checkbox mr-1 mb-1") + cb.text } %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-secondary" %>
      </div>
    <% end %>
    <div class="col-12 text-center">
      <%= link_to 'Cancel and return to articles', articles_path %>
    </div>
  </div>
</div>

app/views/articles/_list_articles.html.erb
<% obj.each do |article| %>
  <div class="card mb-3 shadow-sm">
    <div class="card-body">
      <h4><%= link_to article.title, article_path(article) %></h4>
      <p>
        <%= truncate(article.description, length: 100) %>
      </p>
      <div class="article-meta-details">
        <small>Created by: <%= article.user.username %>, <%= time_ago_in_words(article.created_at) %> ago. </small>
      </div>
      <% if article.categories.any? %>
      <p>Categories: <%= render article.categories%></p>
      <% end %>
      <% if logged_in? && (current_user == article.user || current_user.admin? )%>
        <%= link_to "Edit", edit_article_path(article),class: "btn btn-sm btn-primary"  %>
        <%= link_to "Delete", article_path(article),class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure ?"}  %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center">Articles</h1>
<p>
  <%= link_to "Create new article", new_article_path,class: "btn btn-sm btn-success" %>
</p>
<div class="text-center"><%= will_paginate  %></div>
<%= render 'list_articles', obj: @articles %>
<div class="text-center"><%= will_paginate %></div>

app/views/articles/new.html.erb
<h1 class="text-center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<div class="row">
  <div class="col mb-3">
    <%= link_to gravatar_for(@article.user, size: 30), user_path(@article.user) %>
    <%=link_to @article.user.username, user_path(@article.user)%>
  </div>
</div>
<div class="card text-center">
  <div class="card-header">
    Description
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(@article.description) %></p>
    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    <% if logged_in? && (current_user == @article.user || current_user.admin? )%>
      <%= link_to "Edit", edit_article_path(@article), class:"btn btn-sm btn-primary"  %>
      <%= link_to "Delete this article", article_path(@article), class:"btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure you want to delete the article ?"}%>
    <% end %>
    <%= link_to "Return to articles", articles_path, class:"btn btn-sm btn-success"%>
  </div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge badge-info ml-2" %>

app/views/categories/_form.html.erb
<%= render  "shared/errors", obj: @category %>
<div class="row">
  <div class="col-12">
    <%= form_for @category do |f|%>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit submit, class: "btn btn-secondary" %>
      </div>
    <% end %>
    <div class="col-12 text-center">
      <%= link_to 'Cancel and return to categories', categories_path %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Edit category</h1>
<%= render 'form',submit: "Update"%>

app/views/categories/index.html.erb
<h1>Categories</h1>
<div class="row d-flex justify-content-around">
    <div class="col-8 d-flex justify-content-around">
        <%= will_paginate%>
    </div>
        <% @categories.each do |category| %>
    <div class="col-8 border py-3 mb-3 text-center shadow-sm">
            <h5 class=""><%=link_to "#{category.name}", category_path(category)%></h5>
                <small><%= pluralize(category.articles.count, "article") %></small>
    </div>
        <% end %>
        <div class="col-8 d-flex justify-content-around">
        <%= will_paginate%>
        </div>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render 'form',submit: "Add"%>

app/views/categories/show.html.erb
<h1><%= "Category: " + @category.name %></h1>
<% if logged_in? and current_user.admin? %>
<h4><%= link_to "Edit category", edit_category_path(@category), class: "badge badge-lg badge-danger my-3"%></h4>
<% end %>
<div class="row d-flex">
    <div class="col-12 d-flex justify-content-center">
    <%= will_paginate @category_articles %>
    </div>
    <div class="col-12">
        <%= render 'articles/list_articles',obj: @category_articles%>
    </div>
    <div class="col-12 d-flex justify-content-center">
    <%= will_paginate @category_articles %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row mt-3">
  <div class="col-10 offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%="#{name}"%>">
        <a href="#" class="close" data-dismis="alert">&#215</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha Blog", root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class:"nav-link"%>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="actionDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="actionDropdown">
            <%= link_to "New articles", new_article_path, class:"dropdown-item"%>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
            <%= link_to "All categories", categories_path, class:"dropdown-item"%>
            <% Category.all.each do |category| %>
            <%= link_to "#{category.name}", category_path(category), class:"dropdown-item"%>
            <% end %>
            <% if logged_in? && current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to "Create new category", new_category_path, class:"dropdown-item"%>
            <% end %>
          </div>
        </li>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "Admin" if current_user.admin?%> Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Edit your profile", edit_user_path(current_user),class:"dropdown-item" %>
            <%= link_to "View your profile", user_path(current_user),class:"dropdown-item" %>
          </div>
        </li>
        <li><%= link_to 'Log out', logout_path,class:"nav-link", method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', login_path, class:"nav-link" %></li>
        <li><%= link_to 'Sign up', signup_path, class:"nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container mt-5">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-fluid shadow">
  <div class="container text-center">
    <h1 class="display-4 mb-3">Alpha blog</h1>
    <%= link_to 'Sign up now', signup_path, class:"btn btn-primary btn-lg" %>
  </div>
</div>
<%= link_to 'About', about_path %> | 
<%= link_to 'Alpha Blog', articles_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h5><%= pluralize(obj.errors.count, "error") %> prohibited the creation of the article</h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li>
          <%= msg%>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render  "shared/errors", obj: @user %>
<div class="row">
  <div class="col-12">
    <%= form_for @user do |f|%>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit submit, class: "btn btn-secondary" %>
      </div>
    <% end %>
    <div class="col-12 text-center">
      <%= link_to 'Cancel and return to articles', articles_path %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class=text-center>Edit your account</h1>
<%= render 'form', submit: "Save" %>

app/views/users/index.html.erb
<h1>All users</h1>
<div class="row">
  <div class="col-4 offset-4">
    <% @users.each do |user| %>
      <div class="card bg-light mb-3 text-center mr-4" style="max-width: 18rem;">
        <div class="card-header"><%=link_to user.username, user_path(user)%></div>
        <div class="card-body">
          <%= link_to gravatar_for(user), user_path(user) %>
          <p class="card-text"><small><%= pluralize(user.articles.count, "article") if user.articles%></small></p>
          <% if logged_in? and current_user.admin? %>
            <p><%= link_to "Delete user", user_path(user), method: :delete, data: { confirm: "Are you sure you wan to delete this user ?"}%></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form', submit: "Register"  %>

app/views/users/show.html.erb
<h1 class="text-center">Your account</h1>
<div class="row">
  <div class="col-4 offset-4 text-center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<div class="row">
  <div class="col-12 mt-4">
    <h4 class="text-center">
      <%= @user.username%>'s articles
    </h4>
    <div class="text-center"><%= will_paginate @user_articles  %></div>
    <%= render "articles/list_articles", obj: @user_articles %>
  </div>
</div>